### ISSUE TITLE
Remove jackson-datatype-guava dependency?

### ISSUE THREAD

**Issue by youngm** [palantir/human-readable-types#600]
I like this library very much. It is exactly what I was looking for. However, I like libraries I use to keep transitive dependencies to a minimum The small palantir dependencies are fine. But, guava is a different matter. I'd prefer not to bring `guava` into my project.

It doesn't appear that `jackson-datatype-guava` is required as a runtime dependency. I've excluded it from my project. I'm not too familiar with Gradle. But, in Maven you can mark a dependency as `optional`, which may be appropriate here. It would also be nice to have some assurance that the library won't evolve to add as a runtime dependency in the future.

Thanks for the awesome library!

**Comment by schlosna** [comment]
The transitive dependency footprint should be much smaller as of [release 1.7.0](https://github.com/palantir/human-readable-types/releases/tag/1.7.0)
